services:
  # === DATABASE ===
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-net

  # === REDIS ===
  redis:
    image: redis:7-alpine
    container_name: redis_app
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

  # === KAFKA CLUSTER ===
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-net

  # === AUTH SERVICE ===
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_service
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecret
    ports:
      - "3001:3000"
      - "50051:50051"
    networks:
      - app-net

  # === FILE SERVICE ===
  file-service:
    build:
      context: .
      dockerfile: ./file-service/Dockerfile
    container_name: file_app
    restart: always
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_CONTAINER_AVATARS: ${AZURE_STORAGE_CONTAINER_AVATARS}
      AZURE_STORAGE_CONTAINER_VIDEOS: ${AZURE_STORAGE_CONTAINER_VIDEOS}
    ports:
      - "3003:3000"
      - "50052:50052"
    networks:
      - app-net

  # === MOVIE SERVICE ===
  movie-service:
    build:
      context: .
      dockerfile: ./movie-service/Dockerfile
    container_name: movie_app
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: movie_service
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka:9092
    ports:
      - "3002:3000"
      - "50053:50053"
    networks:
      - app-net

  # === TRANSCODING SERVICE ===
  transcoding-service:
    build:
      context: .
      dockerfile: ./transcoding-service/Dockerfile
    container_name: transcoding_app
    restart: always
    depends_on:
      - kafka
      - file-service
    environment:
      KAFKA_BROKER: kafka:9092
      FILE_SERVICE_GRPC_URL: file-service:50052
    ports:
      - "3004:3000"   # REST debug
    networks:
      - app-net

  # === GATEWAY ===
  gateway:
    build: ./gateway
    container_name: gateway_app
    restart: always
    depends_on:
      - auth-service
      - file-service
      - movie-service
      - redis
    environment:
      AUTH_SERVICE_URL: http://auth-service:3000
      FILE_SERVICE_GRPC_URL: grpc://file-service:50052
      FILE_SERVICE_HTTP_URL: http://file-service:3000
      MOVIE_SERVICE_URL: http://movie-service:3000
      COMMENT_SERVICE_URL: http://comment-service:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
